-- AlterTable
ALTER TABLE "admins" ADD COLUMN     "bio" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "phone" VARCHAR(20) NOT NULL DEFAULT '',
ADD COLUMN     "profile" VARCHAR(500) NOT NULL DEFAULT '',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
